"""initial schema

Revision ID: d65bbb2427dd
Revises: 
Create Date: 2026-03-03 19:33:02.348488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd65bbb2427dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('did', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('privacy_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'PARANOID', name='privacylevel'), nullable=True),
    sa.Column('xmr_address', sa.String(length=255), nullable=True),
    sa.Column('base_address', sa.String(length=255), nullable=True),
    sa.Column('solana_address', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'VERIFIED', 'PREMIUM', 'ENTERPRISE', name='agenttier'), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('staked_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('staked_token', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('rate_limit_tier', sa.Enum('LOW', 'STANDARD', 'HIGH', 'UNLIMITED', name='ratelimittier'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name'),
    sa.UniqueConstraint('did')
    )
    op.create_index(op.f('ix_agents_api_key_hash'), 'agents', ['api_key_hash'], unique=False)
    op.create_table('fee_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('usd_value_at_collection', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COLLECTED', 'WITHDRAWN', name='feecollectionstatus'), nullable=True),
    sa.Column('collection_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=10), nullable=False),
    sa.Column('available', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('pending', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('total_deposited', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('total_withdrawn', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('deposit_address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'token', name='uq_agent_balance')
    )
    op.create_table('agent_reputation',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('successful_transactions', sa.Integer(), nullable=True),
    sa.Column('failed_transactions', sa.Integer(), nullable=True),
    sa.Column('disputed_transactions', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('total_volume_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_fees_paid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('api_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.Text(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_agent_id'), 'audit_log', ['agent_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('from_agent_id', sa.UUID(), nullable=True),
    sa.Column('to_agent_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=12), nullable=True),
    sa.Column('fee_collected', sa.Numeric(precision=20, scale=12), nullable=True),
    sa.Column('payment_type', sa.Enum('P2P', 'HUB_ROUTING', 'ESCROW_DEPOSIT', 'ESCROW_RELEASE', 'CHANNEL_OPEN', 'CHANNEL_CLOSE', 'FEE_COLLECTION', name='paymenttype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'ORPHANED', name='transactionstatus'), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'RETRYING', name='webhookstatus'), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('last_response_code', sa.Integer(), nullable=True),
    sa.Column('last_response_body', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_agent_id'), 'webhook_events', ['agent_id'], unique=False)
    op.create_index('ix_webhook_events_pending', 'webhook_events', ['status', 'next_attempt_at'], unique=False)
    op.create_table('escrow_deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_hash', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('arbiter_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform_fee_percent', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('platform_fee_amount', sa.Numeric(precision=20, scale=12), nullable=True),
    sa.Column('arbiter_fee_percent', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('arbiter_fee_amount', sa.Numeric(precision=20, scale=12), nullable=True),
    sa.Column('timeout_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FUNDED', 'DELIVERED', 'COMPLETED', 'DISPUTED', 'REFUNDED', 'EXPIRED', name='escrowstatus'), nullable=True),
    sa.Column('deposit_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('release_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('multisig_address', sa.String(length=255), nullable=True),
    sa.Column('disputed_at', sa.DateTime(), nullable=True),
    sa.Column('disputed_by', sa.UUID(), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('arbiter_decision', sa.String(length=20), nullable=True),
    sa.Column('arbiter_signature', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('funded_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arbiter_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['deposit_tx_hash'], ['transactions.tx_hash'], ),
    sa.ForeignKeyConstraint(['disputed_by'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['release_tx_hash'], ['transactions.tx_hash'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_hash')
    )
    op.create_table('hub_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=False),
    sa.Column('to_agent_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('fee_percent', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('fee_collected', sa.Boolean(), nullable=True),
    sa.Column('fee_collected_at', sa.DateTime(), nullable=True),
    sa.Column('instant_confirmation', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SETTLED', 'FAILED', name='hubroutestatus'), nullable=True),
    sa.Column('settlement_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['settlement_tx_hash'], ['transactions.tx_hash'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_hub_routes_from_agent_id'), 'hub_routes', ['from_agent_id'], unique=False)
    op.create_index(op.f('ix_hub_routes_to_agent_id'), 'hub_routes', ['to_agent_id'], unique=False)
    op.create_table('payment_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_hash', sa.String(length=64), nullable=False),
    sa.Column('agent_a_id', sa.UUID(), nullable=False),
    sa.Column('agent_b_id', sa.UUID(), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'CLOSING', 'CLOSED', 'DISPUTED', name='channelstatus'), nullable=True),
    sa.Column('funding_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('closing_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('multisig_address', sa.String(length=255), nullable=True),
    sa.Column('current_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('funded_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_a_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['agent_b_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['closing_tx_hash'], ['transactions.tx_hash'], ),
    sa.ForeignKeyConstraint(['funding_tx_hash'], ['transactions.tx_hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_hash')
    )
    op.create_table('channel_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('balance_a', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('balance_b', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('signature_a', sa.Text(), nullable=True),
    sa.Column('signature_b', sa.Text(), nullable=True),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['payment_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'sequence_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_states')
    op.drop_table('payment_channels')
    op.drop_index(op.f('ix_hub_routes_to_agent_id'), table_name='hub_routes')
    op.drop_index(op.f('ix_hub_routes_from_agent_id'), table_name='hub_routes')
    op.drop_table('hub_routes')
    op.drop_table('escrow_deals')
    op.drop_index('ix_webhook_events_pending', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_agent_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_audit_log_agent_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('api_sessions')
    op.drop_table('agent_reputation')
    op.drop_table('agent_balances')
    op.drop_table('fee_collections')
    op.drop_index(op.f('ix_agents_api_key_hash'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
